Skip to content
Search or jump to…
Pull requests
Issues
Marketplace
Explore
 
@saeediqbalofficial 
saeediqbalofficial
/
Basic-Counter-App-React-Javascript
Public
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
Basic-Counter-App-React-Javascript/.github/workflows/Auto_Deploy.yml
@saeediqbalofficial
saeediqbalofficial Update Auto_Deploy.yml
Latest commit 98d6f57 16 days ago
 History
 1 contributor
49 lines (38 sloc)  1.46 KB
   
# This is a basic workflow to help you get started with Actions

name: Auto deployement environment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2-beta
        with:
          version: 12

      # - name: GitHub Action for Yarn
      #   uses: Borales/actions-yarn@v2.1.0
      #   with:
      #     # Yarn command
      #     cmd: install # npm install/ yarn install

      # - name: Creating build
      #   run: yarn build
      - name: installing dependencies
        run: npm install

      - name: Build app with npm run build
        run: npm run build

      - name: installing surge
        run: npm install --global surge

      - name: deploying on surge
        run: surge ./build http://saeed_reacttodo.surge.sh/ --token ${{secrets.SURGE_TOKEN}}
